FROM ubuntu:16.04
MAINTAINER JuanCordobaGurpo29
RUN apt-get update
RUN apt-get install apache2 -y
RUN apt-get install python-software-properties -y
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:openjdk-r/ppa 
RUN echo "<h1>Apache with Docker</h1>" > /var/www/html/index.html
EXPOSE 80
CMD apache2ctl -DFOREGROUND	